{
 "title": "Общее отображение",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency (p50, p95, p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущее количество запросов в обработке",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}